# Generated by Django 4.2.2 on 2023-06-26 16:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_ingredientsinrecipe_recipe_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shoppingcart',
            options={'verbose_name': 'Корзина покупок', 'verbose_name_plural': 'Корзина покупок'},
        ),
        migrations.AlterField(
            model_name='ingredientsinrecipe',
            name='amount',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0, 'Неправильное значение amount Это поле должно содержать число больше "0"')], verbose_name='Количество ингредиента числом'),
        ),
    ]
