# Generated by Django 4.2.2 on 2023-07-01 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_alter_recipe_options_recipe_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredients',
            name='name',
            field=models.CharField(max_length=96, verbose_name='Название ингредиента'),
        ),
    ]
