# Generated by Django 4.2.2 on 2023-06-11 18:56

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0004_alter_recipeingredient_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ShoppingСart',
            new_name='ShoppingCart',
        ),
    ]
