# Generated by Django 4.2.2 on 2023-06-21 17:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_options_alter_subscriptions_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(error_messages={'max_length': 'Поле должно быть короче 150 символов'}, max_length=254, unique=True, verbose_name='Электронная почта пользователя'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(error_messages={'max_length': 'Поле должно быть короче 150 символов'}, max_length=150, verbose_name='Имя пользователя'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(error_messages={'max_length': 'Поле должно быть короче 150 символов'}, max_length=150, verbose_name='Фамилия пользователя'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(error_messages={'max_length': 'Поле должно быть короче 150 символов'}, max_length=150, unique=True, validators=[django.core.validators.RegexValidator('^[\\w.@+-]+\\Z', 'Неправильное значение пользователя Это поле может содержать только буквы, цифры, а также символы ".@+-"')], verbose_name='Никнейм пользователя'),
        ),
    ]
